name: Synthetics

on:
  push:
    branches: [ enes/test-cache ]

env:
  FILENAME: 1GB.bin

jobs:
  save:
    runs-on: ubicloud-standard-4
    steps:
      - name: download hetzner test file
        run: |
          sudo apt-get update && sudo apt-get install -y aria2
          aria2c -x 10 "https://fsn1-speed.hetzner.com/${{ env.FILENAME }}"

      - uses: actions/cache/save@v6
        with:
          path: ${{ env.FILENAME }}
          key: cache-${{ env.FILENAME }}-${{ github.run_id }}

      - name: Print cache proxy logs
        if: always()
        run: sudo cat /var/log/cacheproxy.log

  restore:
    needs: save
    strategy:
      matrix:
        index: [1]
    runs-on: ubicloud-standard-4
    name: restore ${{ matrix.index }}
    steps:
      - uses: actions/cache/restore@v6
        with:
          path: ${{ env.FILENAME }}
          key: cache-${{ env.FILENAME }}-${{ github.run_id }}

      - name: Print cache proxy logs
        if: always()
        run: sudo cat /var/log/cacheproxy.log
